services:
  httpx:
    image: ossrs/httpx:1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.nginx.rule=Host(`s.zaytcev.com`)
      - traefik.http.routers.nginx.middlewares=secure-headers
      - traefik.http.routers.nginx.entryPoints=https
      - traefik.http.routers.nginx.tls=true
      - traefik.http.routers.nginx.tls.certResolver=letsEncrypt
    command: [
      './bin/httpx-static',
      '-http', '80',
      '-proxy', 'http://signal:1989/sig',
      '-proxy', 'http://srs:1985/rtc',
      '-proxy', 'http://signal-web:80/',
    ]
    networks:
      - traefik-public

  signal:
    image: zaytcevcom/signal:1.0.0
    restart: always
    networks:
      - traefik-public

  signal-web:
    image: zaytcevcom/signal-web:1.0.0
    restart: always
    networks:
      - traefik-public

  srs:
    image: ossrs/srs:5
    ports:
      - "1935:1935"
      - "8080:8080"
      - "1985:1985"
      - "8000:8000/udp"
    restart: always
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
