version: "3.9"

services:
  signal:
    image: zaytcevcom/signal:1.0.0
    restart: always
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.routers.signal.rule=Host(`signal.zaytcev.com`)
      - traefik.http.routers.signal.rule=Host(`signal.zaytcev.com`) || Host(`www.signal.zaytcev.com`)
      - traefik.http.services.signal.loadBalancer.server.port=80
      - traefik.http.middlewares.signal-redirect.redirectRegex.regex=^(https?://)www.signal.zaytcev.com/(.*)$$
      - traefik.http.middlewares.signal-redirect.redirectRegex.replacement=$${1}signal.zaytcev.com/$${2}
      - traefik.http.middlewares.signal-redirect.redirectRegex.permanent=true
      - traefik.http.routers.signal.middlewares=signal-redirect,secure-headers
      - traefik.http.routers.signal.entryPoints=https
      - traefik.http.routers.signal.tls=true
      - traefik.http.routers.signal.tls.certResolver=letsEncrypt
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
